config/routes.rb
Bookhub::Application.routes.draw do
  resources :polls do
    resources :options do
      resources :votes
    end

    member do
      put :close
    end
  end

  root :to => "polls#index"

  mount AuthensiveClient::Engine, at: "/session"
end

app/models/option.rb
class Option < ActiveRecord::Base
  attr_accessible :note, :poll_id, :title, :url

  belongs_to :poll
  has_many :votes

  validates_uniqueness_of :title, :scope => :poll_id

  def vote_count
    votes.count
  end

  def close
    self.accepted = (votes.count >= poll.minimum_votes)
    self.save
  end
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :description, :title, :minimum_votes

  validates_presence_of :title, :description

  has_many :options

  def close
    self.open = false
    options.each{|option| option.close }
    self.save
  end

  def closed?
    !open
  end

  def self.active
    where(:open => true)
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :option_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper AuthensiveClient::Engine.helpers
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  def new
    @poll = Poll.find(params[:poll_id])
    @option = @poll.options.new
  end

  def create
    poll = Poll.find(params[:poll_id])
    option = poll.options.new(params[:option])
    option.save
    redirect_to poll
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @polls = Poll.active
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(params[:poll])
    @poll.save
    redirect_to @poll
  end

  def show
    @poll = Poll.find(params[:id])
  end

  def close
    poll = Poll.find(params[:id])
    poll.close
    redirect_to poll
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    option = Option.find(params[:option_id])
    vote = option.votes.new
    vote.save
    redirect_to poll_path(option.poll_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookhub</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <div id='current_user'>
    <p>Current User: <%= current_user.inspect %></p>
    <p>Session <%= session.inspect %></p>
    <%= link_to 'logout', authensive_client.logout_path %>
  </div>
<% else %>
  <%= link_to 'Login with Github', 'http://localhost:4567/login?callback=http://localhost:3000/session/login&return_to=http://localhost:3000/polls/' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/options/_option.html.erb
<div class='option' id='option-<%= option.id %>'>
  <h4 class='title'><%= option.title %></h4>
  <p class='note'><%= option.note %></p>
  <p class='url'><%= option.url %></p>
  <p class='votes'>
    Votes: <%= option.vote_count %>
    <% if @poll.open %>
      <%= button_to "+1", poll_option_votes_path(@poll, option), :id => "plus_one-option_#{option.id}" %>
    <% else %>
      <% if option.accepted? %>
        <span class='accepted'>Accepted</span>
      <% else %>
        <span class='not_accepted'>Not Accepted</span>
      <% end %>
    <% end %>
  </p>
</div>

app/views/options/new.html.erb
<h1>Add An Option</h1>

<%= form_for [@poll, @option] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :id => 'title' %>
  <%= f.label :note %>
  <%= f.text_field :note, :id => 'note' %>
  <%= f.label :url %>
  <%= f.text_field :url, :id => 'url' %>
  <%= f.submit :id => 'submit' %>
<% end %>

app/views/polls/_poll.html.erb
<div id='<%= dom_id(poll) %>'>
  <h3><%= poll.title %></h3>
  <p><%= poll.description %></p>
</div>

app/views/polls/index.html.erb
<h2>Active Polls</h2>

<div class='polls'>
  <% if @polls.any? %>
    <%= render @polls %>
  <% else %>
    No active polls.
  <% end %>
</div>

<h2>Actions</h2>

<div class='actions'>
  <%= link_to "Create a Poll", new_poll_path, :id => 'new_poll' %>
</div>

app/views/polls/new.html.erb
<h1>Create a new Reading Poll</h1>

<%= form_for @poll do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :id => 'title' %>
  <%= f.label :description %>
  <%= f.text_area :description, :id => 'description' %>
  <%= f.label :minimum_votes %>
  <%= f.text_field :minimum_votes, :id => 'minimum_votes' %>
  <%= f.submit :id => 'submit' %>
<% end %>

app/views/polls/show.html.erb
<h1><%= @poll.title %></h1>

<p><%= @poll.description %></p>

<div id='options'>
  <%= render @poll.options %>
</div>

<% if @poll.open? %>
  <%= link_to "Add an Option", new_poll_option_path(@poll), :id => 'add_option' %>
  <%= button_to "Close Poll", close_poll_path(@poll), :id => 'close_poll', :method => 'put' %>
<% end %>